---

- name: enable process perfdata
  lineinfile: 
    dest: "/omd/sites/{{ omd_site }}/etc/pnp4nagios/nagios_gearman.cfg"
    regexp: "^process_performance_data="
    line: "process_performance_data=1"
  become: true
  notify: restart omd

#- name: pythonpath erweitern
#  lineinfile:
#    dest: "/omd/sites/{{ omd_site }}/.profile"
#    line: 'export PYTHONPATH="$OMD_ROOT/lib/python:$OMD_ROOT/local/lib/python:/opt/nts/app/mon20/worker"'
#    regexp: "^export PYTHONPATH="
#  become: true
#  notify: restart omd


- name: symlink omd site central to worker
  file:
    src: /opt/omd/sites/central
    dest: /opt/omd/sites/worker
    state: link
  become: true

- name: create folder /opt/nts
  file:
    dest: /opt/nts
    state: directory
    mode: 0755
    #owner: central
  become: true

#- name: copy /opt/nts/*
#  copy: 
#    src: "files/opt/nts"
#    dest: "/opt"
#    mode: 0755
#    directory_mode: 0755
#    owner: central
#  become: true

- name: symlinks in /opt/nts/bin
  file:
    src:  "/opt/nts/app/mon20/worker/checks/{{ item }}"
    dest: "/opt/nts/bin/{{ item }}"
    state: link
    force: yes
  with_items: 
    - log_viewer
    - show_nagios_health
    - stat_viewer
  become: true
  

- name: copy neamon config
  copy: 
    src: "files/naemon_conf"
    dest: "/opt/omd/sites/{{ omd_site }}/etc/naemon/conf.d"
    mode: 0755
    directory_mode: 0755
    owner: central
  notify: restart omd
  become: true

- name: install resource.cfg 
  template: 
    src: resource_cfg.j2
    dest: "/opt/omd/sites/{{ omd_site }}/etc/naemon/resource.cfg"
    owner: root
    group: root
    mode: 0644
  notify: restart omd
  become: true
  

- name: install mm-plot-template 
  template: 
    src: mm_plot_template.j2
    dest: "/opt/omd/sites/{{ omd_site }}/etc/naemon/conf.d/mm_plot_templates.cfg"
    owner: root
    group: root
    mode: 0644
  notify: restart omd
  become: true
  
- name: copy apache config
  copy: 
    src: "files/apache_conf/nts_maintain.conf"
    dest: "/opt/omd/sites/{{ omd_site }}/etc/apache/conf.d"
    mode: 0755
    directory_mode: 0755
    owner: central
  become: true
  notify: restart omd
  tags: didi

  
  