

- name: restart omd
  shell: >
    omd restart
  become: true


#  
#- name: start omd site
#  shell: >
#    omd start {{ omd_site }}
#  become: true


- name: start omd site
  shell: >
    omd restart
  become: true

  